-- Tables pour myPokemons (à exécuter dans l'éditeur SQL Supabase)

create table if not exists public.users (
  id uuid primary key default gen_random_uuid(),
  email text not null unique,
  username text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.pokemons (
  id bigint generated by default as identity primary key,
  name text not null,
  hp integer not null,
  cp integer not null,
  picture text not null,
  types text[] not null default '{}',
  rarity text not null default '*',
  is_favorite boolean not null default false,
  created timestamptz not null default now()
);

alter table public.pokemons enable row level security;
alter table public.users enable row level security;

create policy "Lecture publique pokemons"
  on public.pokemons for select
  using (true);

create policy "Ecriture publique pokemons"
  on public.pokemons for all
  using (true)
  with check (true);

create policy "Lecture publique users"
  on public.users for select
  using (true);

-- Jeu de données initial
insert into public.pokemons (id, name, hp, cp, picture, types, rarity, is_favorite) values
  (1, 'Bulbizarre', 25, 5, 'https://qvexmeaxafazljnlsjbi.supabase.co/storage/v1/object/public/pokedex/small/1.webp', array['Plante', 'Poison'], '*', false),
  (2, 'Salamèche', 28, 6, 'https://qvexmeaxafazljnlsjbi.supabase.co/storage/v1/object/public/pokedex/small/4.webp', array['Feu'], '*', false),
  (3, 'Carapuce', 21, 4, 'https://qvexmeaxafazljnlsjbi.supabase.co/storage/v1/object/public/pokedex/small/7.webp', array['Eau'], '*', false),
  (4, 'Aspicot', 16, 2, 'https://qvexmeaxafazljnlsjbi.supabase.co/storage/v1/object/public/pokedex/small/13.webp', array['Insecte', 'Poison'], '*', false),
  (5, 'Roucool', 30, 7, 'https://qvexmeaxafazljnlsjbi.supabase.co/storage/v1/object/public/pokedex/small/16.webp', array['Normal', 'Vol'], '*', false),
  (6, 'Rattata', 18, 6, 'https://qvexmeaxafazljnlsjbi.supabase.co/storage/v1/object/public/pokedex/small/19.webp', array['Normal'], '*', false),
  (7, 'Piafabec', 14, 5, 'https://qvexmeaxafazljnlsjbi.supabase.co/storage/v1/object/public/pokedex/small/21.webp', array['Normal', 'Vol'], '*', false),
  (8, 'Abo', 16, 4, 'https://qvexmeaxafazljnlsjbi.supabase.co/storage/v1/object/public/pokedex/small/23.webp', array['Poison'], '**', false),
  (9, 'Pikachu', 21, 7, 'https://qvexmeaxafazljnlsjbi.supabase.co/storage/v1/object/public/pokedex/small/25.webp', array['Electrik'], '***', false),
  (10, 'Sabelette', 19, 3, 'https://qvexmeaxafazljnlsjbi.supabase.co/storage/v1/object/public/pokedex/small/27.webp', array['Normal'], '*', false),
  (11, 'Mélofée', 25, 5, 'https://qvexmeaxafazljnlsjbi.supabase.co/storage/v1/object/public/pokedex/small/35.webp', array['Fée'], '****', false),
  (12, 'Groupix', 17, 8, 'https://qvexmeaxafazljnlsjbi.supabase.co/storage/v1/object/public/pokedex/small/37.webp', array['Feu'], '**', false)
on conflict (id) do nothing;

insert into public.users (email, username) values
  ('ash@pokemon.fr', 'Sacha'),
  ('misty@pokemon.fr', 'Ondine')
on conflict (email) do nothing;

select setval(pg_get_serial_sequence('public.pokemons', 'id'), (select max(id) from public.pokemons));
