-- ============================================================
-- myPokemons — SCRIPT SQL COMPLET
--
-- Contenu :
--   - Tables : pokemons, users, user_favorites
--   - Auth   : register_user / login_user (mot de passe chiffre)
--   - RLS    : politiques de securite
--   - Data   : 12 pokemons + 2 comptes de test + favoris
--
-- Comptes de test :
--   ash@pokemon.fr   / Sacha   / mot de passe : pokemon123
--   misty@pokemon.fr / Ondine  / mot de passe : pokemon123
-- ============================================================

create extension if not exists pgcrypto with schema extensions;

grant usage on schema extensions to postgres, anon, authenticated, service_role;

-- ------------------------------------------------------------
-- NETTOYAGE
-- ------------------------------------------------------------
drop function if exists public.login_user(text, text);
drop function if exists public.register_user(text, text, text);

drop policy if exists "Lecture publique pokemons" on public.pokemons;
drop policy if exists "Ecriture publique pokemons" on public.pokemons;
drop policy if exists "Lecture profils users" on public.users;
drop policy if exists "Lecture favoris" on public.user_favorites;
drop policy if exists "Ajout favoris" on public.user_favorites;
drop policy if exists "Suppression favoris" on public.user_favorites;

drop table if exists public.user_favorites;
drop table if exists public.users cascade;
drop table if exists public.pokemons cascade;

-- ------------------------------------------------------------
-- 1. TABLE POKEMONS
-- ------------------------------------------------------------
create table public.pokemons (
  id bigint generated by default as identity primary key,
  name text not null,
  hp integer not null,
  cp integer not null,
  picture text not null,
  types text[] not null default '{}',
  rarity text not null default '*',
  created timestamptz not null default now()
);

alter table public.pokemons enable row level security;

create policy "Lecture publique pokemons"
  on public.pokemons for select
  using (true);

create policy "Ecriture publique pokemons"
  on public.pokemons for all
  using (true)
  with check (true);

-- ------------------------------------------------------------
-- 2. TABLE USERS (mot de passe chiffre en base)
-- ------------------------------------------------------------
create table public.users (
  id uuid primary key default gen_random_uuid(),
  email text not null unique,
  username text not null,
  password text not null,
  created_at timestamptz not null default now()
);

alter table public.users enable row level security;

create policy "Lecture profils users"
  on public.users for select
  using (true);

revoke all on public.users from anon, authenticated;
grant select (id, email, username, created_at) on public.users to anon, authenticated;

create or replace function public.register_user(
  p_email text,
  p_password text,
  p_username text
)
returns json
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  v_user public.users%rowtype;
begin
  if length(p_password) < 6 then
    raise exception 'Le mot de passe doit contenir au moins 6 caracteres';
  end if;

  insert into public.users (email, username, password)
  values (p_email, p_username, extensions.crypt(p_password, extensions.gen_salt('bf')))
  returning * into v_user;

  return json_build_object(
    'id', v_user.id,
    'email', v_user.email,
    'username', v_user.username,
    'created_at', v_user.created_at
  );
end;
$$;

create or replace function public.login_user(
  p_email text,
  p_password text
)
returns json
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  v_user public.users%rowtype;
begin
  select * into v_user
  from public.users
  where email = p_email;

  if v_user.id is null then
    raise exception 'Email ou mot de passe incorrect';
  end if;

  if v_user.password is distinct from extensions.crypt(p_password, v_user.password) then
    raise exception 'Email ou mot de passe incorrect';
  end if;

  return json_build_object(
    'id', v_user.id,
    'email', v_user.email,
    'username', v_user.username,
    'created_at', v_user.created_at
  );
end;
$$;

grant execute on function public.register_user(text, text, text) to anon, authenticated;
grant execute on function public.login_user(text, text) to anon, authenticated;

-- ------------------------------------------------------------
-- 3. TABLE USER_FAVORITES (favoris par utilisateur)
-- ------------------------------------------------------------
create table public.user_favorites (
  user_id uuid not null references public.users(id) on delete cascade,
  pokemon_id bigint not null references public.pokemons(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (user_id, pokemon_id)
);

alter table public.user_favorites enable row level security;

create policy "Lecture favoris"
  on public.user_favorites for select
  using (true);

create policy "Ajout favoris"
  on public.user_favorites for insert
  with check (true);

create policy "Suppression favoris"
  on public.user_favorites for delete
  using (true);

-- ------------------------------------------------------------
-- 4. INSERTION DES POKEMONS (12)
-- ------------------------------------------------------------
insert into public.pokemons (id, name, hp, cp, picture, types, rarity, created) values
  (1,  'Bulbizarre', 25, 5, 'https://qvexmeaxafazljnlsjbi.supabase.co/storage/v1/object/public/pokedex/small/1.webp',  array['Plante', 'Poison'], '*',    '2024-02-01 10:00:00+00'),
  (2,  'Salamèche',  28, 6, 'https://qvexmeaxafazljnlsjbi.supabase.co/storage/v1/object/public/pokedex/small/4.webp',  array['Feu'],                 '*',    '2024-02-02 10:00:00+00'),
  (3,  'Carapuce',   21, 4, 'https://qvexmeaxafazljnlsjbi.supabase.co/storage/v1/object/public/pokedex/small/7.webp',  array['Eau'],                 '*',    '2024-02-03 10:00:00+00'),
  (4,  'Aspicot',    16, 2, 'https://qvexmeaxafazljnlsjbi.supabase.co/storage/v1/object/public/pokedex/small/13.webp', array['Insecte', 'Poison'], '*',    '2024-02-04 10:00:00+00'),
  (5,  'Roucool',    30, 7, 'https://qvexmeaxafazljnlsjbi.supabase.co/storage/v1/object/public/pokedex/small/16.webp', array['Normal', 'Vol'],     '*',    '2024-02-05 10:00:00+00'),
  (6,  'Rattata',    18, 6, 'https://qvexmeaxafazljnlsjbi.supabase.co/storage/v1/object/public/pokedex/small/19.webp', array['Normal'],              '*',    '2024-02-06 10:00:00+00'),
  (7,  'Piafabec',   14, 5, 'https://qvexmeaxafazljnlsjbi.supabase.co/storage/v1/object/public/pokedex/small/21.webp', array['Normal', 'Vol'],     '*',    '2024-02-07 10:00:00+00'),
  (8,  'Abo',        16, 4, 'https://qvexmeaxafazljnlsjbi.supabase.co/storage/v1/object/public/pokedex/small/23.webp', array['Poison'],              '**',   '2024-02-08 10:00:00+00'),
  (9,  'Pikachu',    21, 7, 'https://qvexmeaxafazljnlsjbi.supabase.co/storage/v1/object/public/pokedex/small/25.webp', array['Electrik'],            '***',  '2024-02-09 10:00:00+00'),
  (10, 'Sabelette',  19, 3, 'https://qvexmeaxafazljnlsjbi.supabase.co/storage/v1/object/public/pokedex/small/27.webp', array['Normal'],              '*',    '2024-02-10 10:00:00+00'),
  (11, 'Mélofée',    25, 5, 'https://qvexmeaxafazljnlsjbi.supabase.co/storage/v1/object/public/pokedex/small/35.webp', array['Fée'],                 '****', '2024-02-11 10:00:00+00'),
  (12, 'Groupix',    17, 8, 'https://qvexmeaxafazljnlsjbi.supabase.co/storage/v1/object/public/pokedex/small/37.webp', array['Feu'],                 '**',   '2024-02-12 10:00:00+00')
on conflict (id) do nothing;

select setval(
  pg_get_serial_sequence('public.pokemons', 'id'),
  coalesce((select max(id) from public.pokemons), 1)
);

-- ------------------------------------------------------------
-- 5. INSERTION DES UTILISATEURS DE TEST
-- Mot de passe pour les 2 comptes : pokemon123
-- ------------------------------------------------------------
insert into public.users (id, email, username, password, created_at) values
  ('11111111-1111-1111-1111-111111111111', 'ash@pokemon.fr',   'Sacha',  extensions.crypt('pokemon123', extensions.gen_salt('bf')), '2024-01-01 08:00:00+00'),
  ('22222222-2222-2222-2222-222222222222', 'misty@pokemon.fr', 'Ondine', extensions.crypt('pokemon123', extensions.gen_salt('bf')), '2024-01-02 08:00:00+00')
on conflict (id) do update set
  email = excluded.email,
  username = excluded.username,
  password = excluded.password;

-- ------------------------------------------------------------
-- 6. INSERTION DES FAVORIS DE TEST
-- ------------------------------------------------------------
insert into public.user_favorites (user_id, pokemon_id, created_at) values
  ('11111111-1111-1111-1111-111111111111', 1,  '2024-03-01 12:00:00+00'),  -- Sacha  > Bulbizarre
  ('11111111-1111-1111-1111-111111111111', 9,  '2024-03-01 12:05:00+00'),  -- Sacha  > Pikachu
  ('22222222-2222-2222-2222-222222222222', 3,  '2024-03-02 12:00:00+00'),  -- Ondine > Carapuce
  ('22222222-2222-2222-2222-222222222222', 11, '2024-03-02 12:05:00+00')   -- Ondine > Mélofée
on conflict (user_id, pokemon_id) do nothing;

-- ------------------------------------------------------------
-- VERIFICATION
-- ------------------------------------------------------------
select 'pokemons' as table_name, count(*) as total from public.pokemons
union all
select 'users', count(*) from public.users
union all
select 'user_favorites', count(*) from public.user_favorites;
